# fly.toml app configuration file generated for nexuslab on 2025-06-05T19:31:42-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nexuslab'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_start_machines = false
  auto_stop_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'