"""add fields to projects table

Revision ID: 1c4fad790925
Revises: a41143307b83
Create Date: 2025-05-17 11:49:56.900512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4fad790925'
down_revision: Union[str, None] = 'a41143307b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('priority', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'deadline')
    # ### end Alembic commands ###
