"""Add sort_order to resources

Revision ID: 7be45efa8101
Revises: 42a7f03af296
Create Date: 2025-06-22 15:25:22.971205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be45efa8101'
down_revision: Union[str, None] = '42a7f03af296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('sort_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'sort_order')
    # ### end Alembic commands ###
