"""add fields to projects table

Revision ID: a41143307b83
Revises: 8357190aea3c
Create Date: 2025-05-17 11:46:33.682891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41143307b83'
down_revision: Union[str, None] = '8357190aea3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('purpuse', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('desired_outcome', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'desired_outcome')
    op.drop_column('projects', 'purpuse')
    # ### end Alembic commands ###
