"""add_task_order_field_to_tasks

Revision ID: b55a1ff71ec4
Revises: 99b39dd717ef
Create Date: 2025-05-21 16:25:10.161563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b55a1ff71ec4"
down_revision: Union[str, None] = "99b39dd717ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename 'order' column to 'task_order' to match the model
    op.alter_column("tasks", "order", new_column_name="task_order")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename 'task_order' back to 'order'
    op.alter_column("tasks", "task_order", new_column_name="order")
    # ### end Alembic commands ###
