"""rename_task_order_to_sort_order

Revision ID: ea95bc30586d
Revises: b55a1ff71ec4
Create Date: 2025-05-21 16:34:19.267185

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ea95bc30586d"
down_revision: Union[str, None] = "b55a1ff71ec4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "task_order", new_column_name="sort_order")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "sort_order", new_column_name="task_order")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
